### ISSUE TITLE
Shall i add ai to your bot LMAO. 

### ISSUE THREAD

**Issue by Skorchekd** [pdt1806/refiner-discord-bot#2]
if with your permission can i make it into an ai waifu type thingy lol. with a personality you approve of course.

**Comment by pdt1806** [comment]
If you want to contribute to Refiner (and Discord Status as Image) specifically, consider forking this repo and open a pull request after you have made changes to it.

In case you think this code can serve as the foundation for your next bot, feel free to use it as a reference and there's no need to give me credit!
